# [WSL2]
from pathlib import Path

from sqlalchemy import create_engine, inspect
from sqlalchemy.orm import declarative_base, sessionmaker

from app.config import settings


engine = create_engine(
    settings.sqlite_url,
    connect_args={"check_same_thread": False},
    future=True,
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine, future=True)
Base = declarative_base()

_APP_TABLES = {"incidents", "blocked_ips", "flow_snapshots"}


def init_db() -> None:
    """Error.md #29 — schema now comes from Alembic migrations, not
    create_all(), so future column/table changes go through versioned
    migration files instead of silently doing nothing against an existing
    database (create_all only ever creates missing tables; it never alters
    existing ones)."""
    from app.models import incident  # noqa: F401 — registers models on Base.metadata

    from alembic import command
    from alembic.config import Config

    backend_dir = Path(__file__).resolve().parent.parent
    alembic_cfg = Config(str(backend_dir / "alembic.ini"))
    alembic_cfg.set_main_option("script_location", str(backend_dir / "migrations"))
    alembic_cfg.set_main_option("sqlalchemy.url", settings.sqlite_url)

    existing_tables = set(inspect(engine).get_table_names())
    if existing_tables & _APP_TABLES and "alembic_version" not in existing_tables:
        # A database created by the old create_all() before Alembic existed
        # here. Its schema already matches the baseline migration exactly
        # (that migration was autogenerated from these same models) — stamp
        # it at the BASELINE revision, then upgrade() applies any subsequent
        # migrations (e.g. adding data_source columns, enforcement_actions
        # table) that a head stamp would have incorrectly skipped.
        command.stamp(alembic_cfg, "96d6eba3e436")
        command.upgrade(alembic_cfg, "head")
    else:
        command.upgrade(alembic_cfg, "head")


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

