"""baseline schema

Revision ID: 96d6eba3e436
Revises: 
Create Date: 2026-08-22 12:33:31.946887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d6eba3e436'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_ips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('attack_type', sa.String(length=50), nullable=True),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('blockchain_tx', sa.String(length=120), nullable=True),
    sa.Column('enforcement_status', sa.String(length=40), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_ips_blocked_at'), 'blocked_ips', ['blocked_at'], unique=False)
    op.create_index(op.f('ix_blocked_ips_ip_address'), 'blocked_ips', ['ip_address'], unique=True)
    op.create_table('flow_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=False),
    sa.Column('dst_port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=12), nullable=False),
    sa.Column('packet_count', sa.Integer(), nullable=False),
    sa.Column('byte_count', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('tcp_flags', sa.Integer(), nullable=False),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_snapshots_captured_at'), 'flow_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_flow_snapshots_dst_ip'), 'flow_snapshots', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_flow_snapshots_src_ip'), 'flow_snapshots', ['src_ip'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('attack_type', sa.String(length=50), nullable=False),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('raw_flow_json', sa.Text(), nullable=True),
    sa.Column('blockchain_tx', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('enforcement_status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_source_ip'), 'incidents', ['source_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_source_ip'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_flow_snapshots_src_ip'), table_name='flow_snapshots')
    op.drop_index(op.f('ix_flow_snapshots_dst_ip'), table_name='flow_snapshots')
    op.drop_index(op.f('ix_flow_snapshots_captured_at'), table_name='flow_snapshots')
    op.drop_table('flow_snapshots')
    op.drop_index(op.f('ix_blocked_ips_ip_address'), table_name='blocked_ips')
    op.drop_index(op.f('ix_blocked_ips_blocked_at'), table_name='blocked_ips')
    op.drop_table('blocked_ips')
    # ### end Alembic commands ###
