"""add enforcement_actions table and data_source columns

Revision ID: d4295f4f8129
Revises: 96d6eba3e436
Create Date: 2026-08-22 14:05:07.393860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4295f4f8129'
down_revision: Union[str, Sequence[str], None] = '96d6eba3e436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enforcement_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('blockchain_tx', sa.String(length=120), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enforcement_actions_created_at'), 'enforcement_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_enforcement_actions_incident_id'), 'enforcement_actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_enforcement_actions_ip_address'), 'enforcement_actions', ['ip_address'], unique=False)
    # server_default is required here: both tables can already have rows
    # (this migration runs against real populated databases, not just fresh
    # ones), and a NOT NULL column with no default fails against existing
    # rows. Every pre-existing row genuinely was manually-sourced data by
    # definition (data_source didn't exist before this migration), so
    # backfilling "manual" is accurate, not just a placeholder.
    op.add_column('flow_snapshots', sa.Column('data_source', sa.String(length=20), nullable=False, server_default='manual'))
    op.add_column('incidents', sa.Column('data_source', sa.String(length=20), nullable=False, server_default='manual'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'data_source')
    op.drop_column('flow_snapshots', 'data_source')
    op.drop_index(op.f('ix_enforcement_actions_ip_address'), table_name='enforcement_actions')
    op.drop_index(op.f('ix_enforcement_actions_incident_id'), table_name='enforcement_actions')
    op.drop_index(op.f('ix_enforcement_actions_created_at'), table_name='enforcement_actions')
    op.drop_table('enforcement_actions')
    # ### end Alembic commands ###
