"""Assemble ML/retrain_logs/live_loop_run.txt from the run's own outputs. Nothing
here is typed in from memory: the log lines, health payloads and traffic timeline
are read from the files the run wrote."""
import json
import re
from collections import Counter
from pathlib import Path

G = Path("C:/dev/gs_live")
REPO = Path("C:/dev/GraphSentinal")
OUT = REPO / "ML" / "retrain_logs" / "live_loop_run.txt"
CAP = REPO / "ML" / "retrain_logs" / "live_loop"
CAP.mkdir(parents=True, exist_ok=True)


def text(name):
    return (G / name).read_text(encoding="utf-8", errors="replace").replace("\x00", "").replace("\r\n", "\n")


def lines_of(name, keep):
    return [l for l in text(name).splitlines() if keep(l)]


run2_log = lines_of("backend.log", lambda l: l.strip() and "FlowParser" not in l)
run1_log = lines_of("run1_backend.log", lambda l: "graphsentinel" in l)
h1 = json.loads(text("run1_health.json"))
h2 = json.loads(text("run2_health.json"))

# The capture for run 2, raw, as OVS printed it.
cap2 = text("dump_flows_capture.txt")
cap1 = text("run1_dump_flows.txt")
(CAP / "dump_flows_run2.txt").write_text(cap2, encoding="utf-8", newline="\n")
(CAP / "dump_flows_run1.txt").write_text(cap1, encoding="utf-8", newline="\n")

rules = [re.search(r"rule (\S+)/(\S+) on (\S+) -> (\S+?):(\d+) proto", l).groups()
         for l in run2_log if ": rule " in l]
tally = Counter((src, dst, port, cls) for cls, _, src, dst, port in rules)
polls2 = cap2.count("=== ")
dumps = [d for d in cap2.split("=== ")[1:]]
per_dump = [sum(1 for l in d.splitlines()[1:] if "nw_src=" in l or "arp_spa=" in l) for d in dumps]


def mon(h):
    m, c = h["monitor"], h["ml_v2"]["client"]
    return {
        "poll_counts": m["poll_counts"], "last_poll_status": m["last_poll_status"],
        "v2_provenance": m["v2_provenance"], "v2_windows_closed": m["v2_windows_closed"],
        "v2_last_error": m["v2_last_error"],
        "client": {k: c[k] for k in ("windows_seen", "windows_unscored", "unscored_rate",
                                     "flows_sent", "flows_dropped_in_mapping", "last_error")},
        "policy_sha256": h["ml_v2"]["policy"]["sha256"],
        "policy_enforceable": h["ml_v2"]["policy"]["enforceable"],
        "policy_alert_only": h["ml_v2"]["policy"]["alert_only"],
        "policy_dry_run": h["ml_v2"]["policy"]["dry_run"],
        "v1": h["v1"],
    }


out = []
w = out.append
w("GraphSentinel -- the live loop, run once on real Open vSwitch flows")
w("=" * 68)
w("")
w("WHAT THIS IS")
w("  Real traffic between Mininet hosts, through a real OVS bridge, polled by the")
w("  backend's own monitor through the project's own enforcement daemon:")
w("    OVS (s1) -> enforcement_daemon.py `ovs-ofctl dump-flows s1` -> flow_parser")
w("    -> monitor -> provenance gate -> v2 client -> inference service -> rules")
w("    accepted and logged by the backend.")
w("  The `data_source: ovs` tag on every flow was set by flow_parser from the dump")
w("  text. Nothing was tagged by hand and the provenance gate was not changed.")
w("")
w("ROUTE")
w("  Route B, local, no Docker. NOT Colab and NOT a replayed capture: the backend")
w("  polled a live switch every 5 s for the whole run.")
w("    WSL2 Ubuntu 26.04.1, kernel 6.18.33.2-microsoft-standard-WSL2")
w("    Open vSwitch 3.7.1, kernel datapath (openvswitch module loaded), Mininet 2.3.0")
w("    topology: mininet/topologies/base_topology_headless.py, unmodified")
w("      (10 hosts 10.0.0.1-10, one switch s1, fail_mode secure, controller")
w("       ovs-testcontroller via Mininet's OVSController -- it installs one")
w("       exact-match flow per conversation, idle_timeout 60)")
w("    daemon: backend/scripts/enforcement_daemon.py, unmodified, in WSL as root,")
w("      127.0.0.1:50051, reached from Windows through WSL2 localhost forwarding")
w("    backend and inference service: the two uvicorn processes of RUN_GUIDE.md")
w("      section 5, on Windows, Python 3.10.10, torch 2.13.0+cpu. No Ganache, no")
w("      frontend. ENFORCEMENT_MODE=simulated, THREAT_THRESHOLD=0.75,")
w("      DEMO_FALLBACK_FLOWS=false, GS2_ENABLED=true.")
w("    backend started with --log-config so that INFO lines from its own")
w("      `graphsentinel.*` loggers are printed. Under the default start they are")
w("      not: no handler is configured for them and only WARNING and above show.")
w("")
w("TWO RUNS, SAME TRAFFIC SCRIPT")
w("  Run 1 logged rule COUNTS only; the monitor keeps nothing else of a window.")
w("  So one logging change was made (analysis_pipeline_v2.py: one line per rule")
w("  and one per scored window) and the run repeated. Run 2 is the one analysed.")
w("  Both are given below. The two runs are not a variance estimate.")
w("")
w("TRAFFIC (run 2, UTC, from the generator's own log)")
for l in text("traffic.log").splitlines():
    w("  " + l)
w("  All of it was generated by one script written for this run. It is labelled by")
w("  construction (the script knows what it sent), not by a dataset.")
w("")
w("MEMORY")
w("  3,930 MB machine. Free physical memory was between 123 and 643 MB during the")
w("  runs, with Windows memory compression active. The inference service")
w("  segfaulted once at start (exit 139) with 344 MB of virtual memory free, and")
w("  started after the WSL page cache was dropped. NO TIMING in this file means")
w("  anything.")
w("")
w("RUN 2 -- THE BACKEND'S OWN LOG (FlowParser failure lines: none)")
w("-" * 68)
for l in run2_log:
    w(l)
w("")
w("RUN 2 -- /health AFTER THE RUN (monitor, v2 client, policy)")
w("-" * 68)
w(json.dumps(mon(h2), indent=2))
w("")
w("RUN 2 -- WHAT THE RULES WERE MADE ON")
w("-" * 68)
w(f"  {len(rules)} rules admitted across {h2['monitor']['v2_windows_closed']} windows, all dry run.")
for (src, dst, port, cls), n in sorted(tally.items(), key=lambda kv: -kv[1]):
    w(f"    {n} x {cls:<17} {src:>10} -> {dst}:{port}")
w("  What each of those conversations was, from the traffic script:")
w("    10.0.0.7/8 -> 10.0.0.3:80 and 10.0.0.9/10 -> 10.0.0.1:80   benign HTTP fetches")
w("    10.0.0.1 -> 10.0.0.9:<high port>                           the reply to one")
w("    10.0.0.5 -> 10.0.0.4:22                                    the brute-force-shaped")
w("                                                               connections, labelled")
w("                                                               Volumetric_Flood")
w("  The flood itself, 10.0.0.2 -> 10.0.0.3:80 from source port 45000, is in the")
w("  flow table in 14 polls and received NO rule. Its last sighting:")
for l in cap2.splitlines():
    if "nw_src=10.0.0.2,nw_dst=10.0.0.3" in l and "tp_src=45000" in l:
        last = l
w("   " + last)
w("")
w("RUN 2 -- THE POLLS")
w("-" * 68)
w(f"  capture loop: {polls2} dumps, 5 s apart, of the daemon's exact command")
w(f"  parseable flow lines per dump: min {min(per_dump)}, max {max(per_dump)}")
w("  The monitor submits the WHOLE table on every poll, with cumulative counters,")
w("  so one conversation is sent once per poll while it stays in the table. The")
w("  'scored N flow(s)' figures above count those re-submissions, not conversations.")
w("  Raw text: ML/retrain_logs/live_loop/dump_flows_run2.txt (and _run1.txt).")
w("  The capture loop is a second reader beside the daemon, not the daemon's own")
w("  responses: the two read the same table up to 5 s apart.")
w("")
w("RUN 1 -- THE BACKEND'S v2 LINES (counts only)")
w("-" * 68)
for l in run1_log:
    w(l)
w("")
w("RUN 1 -- /health AFTER THE RUN")
w("-" * 68)
w(json.dumps(mon(h1), indent=2))
w("")
OUT.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
print(OUT, len(out), "lines;", "rules", len(rules), dict(Counter(c for c, *_ in rules)))
print({f"{s}->{d}:{p}": n for (s, d, p, c), n in tally.items()})
print("capture bytes", len(cap2), len(cap1), "polls", polls2)
